In [ ]:
import pandas as pd
import glob

df = pd.read_csv('only_talks.csv')
print(f"Dataset shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
df.head()
#df_test = df.head(10)

Dataset shape: (5338, 19)
Columns: ['id', 'title', 'speaker', 'description', 'views', 'duration', 'video_context', 'type', 'url', 'language', 'published_at', 'slug', 'tedcom_percentage', 'youtube_percentage', 'podcasts_percentage', 'topics', 'number_of_topics', 'transcript', 'transcript_length']

,id,title,speaker,description,views,duration,video_context,type,url,language,published_at,slug,tedcom_percentage,youtube_percentage,podcasts_percentage,topics,number_of_topics,transcript,transcript_length
0,160685,"Friendly pizza, UFOs and the joy of AI-generat...",Matan Cohen Grumi,While many rush to create new realities with A...,34512,312,TED2025,TED Stage Talk,https://www.ted.com/talks/matan_cohen_grumi_fr...,en,2025-10-01T14:43:54Z,matan_cohen_grumi_friendly_pizza_ufos_and_the_...,0.274,0.480,0.00,"technology, creativity, AI, social media",4,This is how my sister reacted when I told her ...,3580.0
1,157723,The incredible secrets hidden in your immune s...,Beck Brachman,Your immune system keeps a record of everythin...,67065,278,TED2025,TED Stage Talk,https://www.ted.com/talks/beck_brachman_the_in...,en,2025-09-09T14:58:08Z,beck_brachman_the_incredible_secrets_hidden_in...,0.393,0.471,0.00,"science, innovation, disease, health, cancer, ...",8,Here&apos;s a teaser. What if I told you that ...,3410.0
2,148409,"""The Unprompted,"" a poem that AI will never un...",Salome Agbaroji,What happens when a poet talks back to AI? In ...,269253,300,TED2025,TED Stage Talk,https://www.ted.com/talks/salome_agbaroji_the_...,en,2025-08-25T14:39:52Z,salome_agbaroji_the_unprompted_a_poem_that_ai_...,0.056,0.098,0.83,"social change, poetry, AI, machine learning",4,I fill my empty 3 ams with spineless phone scr...,3153.0
3,148408,A spine-tingling dance of light and shadow,Tony Testa,"Choreographer Tony Testa tap-dances to ""Human ...",30507,157,TED2025,TED Stage Talk,https://www.ted.com/talks/tony_testa_a_spine_t...,en,2025-06-06T14:47:41Z,tony_testa_a_spine_tingling_dance_of_light_and...,0.122,0.826,0.00,"music, performance, dance",3,NaN,0.0
4,147771,How I turned frustration into creative success,Joshua Schachter,"Sharing his accidental journey to viral fame, ...",102867,289,TEDNext 2024,TED Stage Talk,https://www.ted.com/talks/joshua_schachter_how...,en,2025-05-22T15:09:20Z,joshua_schachter_how_i_turned_frustration_into...,0.175,0.737,0.00,"technology, design, computers, robots, creativ...",7,So for many years I&apos;ve been doing compute...,2612.0

In [ ]:
import pandas as pd
import re


def clean_and_split_speakers(speaker_string):
    """
    Nettoie et sépare les noms de speakers
    """
    if pd.isna(speaker_string):
        return []
    
    # Standardiser les séparateurs
    speaker_string = str(speaker_string)
    speaker_string = re.sub(r'\s*&\s*|\s+and\s+|\s+et\s+|\s+und\s+|\s+y\s+', ', ', speaker_string, flags=re.IGNORECASE)
    
    # Supprimer les espaces multiples
    speaker_string = re.sub(r'\s+', ' ', speaker_string)
    
    # Séparer par virgule
    speakers = [s.strip() for s in speaker_string.split(',') if s.strip()]
    
    return speakers

# Ajouter la liste des speakers à la main df pour chaque video (on pourrait remplacer la colonne speaker par ça)
df['speakers_list'] = df['speaker'].apply(clean_and_split_speakers)

# Vérifier les résultats
df.head()

,id,title,speaker,description,views,duration,video_context,type,url,language,published_at,slug,tedcom_percentage,youtube_percentage,podcasts_percentage,topics,number_of_topics,transcript,transcript_length,speakers_list
0,160685,"Friendly pizza, UFOs and the joy of AI-generat...",Matan Cohen Grumi,While many rush to create new realities with A...,34512,312,TED2025,TED Stage Talk,https://www.ted.com/talks/matan_cohen_grumi_fr...,en,2025-10-01T14:43:54Z,matan_cohen_grumi_friendly_pizza_ufos_and_the_...,0.274,0.480,0.00,"technology, creativity, AI, social media",4,This is how my sister reacted when I told her ...,3580.0,[Matan Cohen Grumi]
1,157723,The incredible secrets hidden in your immune s...,Beck Brachman,Your immune system keeps a record of everythin...,67065,278,TED2025,TED Stage Talk,https://www.ted.com/talks/beck_brachman_the_in...,en,2025-09-09T14:58:08Z,beck_brachman_the_incredible_secrets_hidden_in...,0.393,0.471,0.00,"science, innovation, disease, health, cancer, ...",8,Here&apos;s a teaser. What if I told you that ...,3410.0,[Beck Brachman]
2,148409,"""The Unprompted,"" a poem that AI will never un...",Salome Agbaroji,What happens when a poet talks back to AI? In ...,269253,300,TED2025,TED Stage Talk,https://www.ted.com/talks/salome_agbaroji_the_...,en,2025-08-25T14:39:52Z,salome_agbaroji_the_unprompted_a_poem_that_ai_...,0.056,0.098,0.83,"social change, poetry, AI, machine learning",4,I fill my empty 3 ams with spineless phone scr...,3153.0,[Salome Agbaroji]
3,148408,A spine-tingling dance of light and shadow,Tony Testa,"Choreographer Tony Testa tap-dances to ""Human ...",30507,157,TED2025,TED Stage Talk,https://www.ted.com/talks/tony_testa_a_spine_t...,en,2025-06-06T14:47:41Z,tony_testa_a_spine_tingling_dance_of_light_and...,0.122,0.826,0.00,"music, performance, dance",3,NaN,0.0,[Tony Testa]
4,147771,How I turned frustration into creative success,Joshua Schachter,"Sharing his accidental journey to viral fame, ...",102867,289,TEDNext 2024,TED Stage Talk,https://www.ted.com/talks/joshua_schachter_how...,en,2025-05-22T15:09:20Z,joshua_schachter_how_i_turned_frustration_into...,0.175,0.737,0.00,"technology, design, computers, robots, creativ...",7,So for many years I&apos;ve been doing compute...,2612.0,[Joshua Schachter]

In [11]:
# Créer une liste pour le nouveau DataFrame
expanded_rows = []

for idx, row in df.iterrows():
    video_id = row['id']
    views = row['views']
    
    for speaker_name in row['speakers_list']:
        expanded_rows.append({
            'speaker': speaker_name,
            'video_id': video_id,
            'views': views,
            'topics': row['topics'],
        })

# Créer le DataFrame étendu
expanded_df = pd.DataFrame(expanded_rows)
print(f"Nombre total d'entrées : {len(expanded_df)}")
print(f"Nombre de speakers uniques : {expanded_df['speaker'].nunique()}")

expanded_df.head()

Nombre total d'entrées : 5489
Nombre de speakers uniques : 4759

,speaker,video_id,views,topics
0,Matan Cohen Grumi,160685,34512,"technology, creativity, AI, social media"
1,Beck Brachman,157723,67065,"science, innovation, disease, health, cancer, ..."
2,Salome Agbaroji,148409,269253,"social change, poetry, AI, machine learning"
3,Tony Testa,148408,30507,"music, performance, dance"
4,Joshua Schachter,147771,102867,"technology, design, computers, robots, creativ..."

In [ ]:
def aggregate_speaker_data(expanded_df):
    """
    Agrége les données par speaker pour obtenir le format demandé
    """
    # Fonction pour combiner les listes de topics uniques
    def combine_topics(series):
        # Si les topics sont déjà sous forme de liste
        all_topics = []
        for item in series:
            if isinstance(item, list):
                all_topics.extend(item)
            elif pd.notna(item):
                # Si c'est une chaîne, on peut la traiter
                all_topics.append(str(item))
        # Retirer les doublons
        return list(set(all_topics))
    
    # Agréger les données
    speaker_agg = expanded_df.groupby('speaker').agg(
        video_ids=('video_id', list),  # Liste des IDs de vidéos
        videos=('video_id', 'count'),  # Nombre de vidéos
        views=('views', 'sum'),  # Somme des vues
        topics=('topics', combine_topics)  # Tous les topics uniques
    ).reset_index()
    
    # Calculer la moyenne des vues
    speaker_agg['average_views'] = speaker_agg['views'] / speaker_agg['videos']
    
    # Arrondir la moyenne
    speaker_agg['average_views'] = speaker_agg['average_views'].round(2)
    
    # Trier par nombre de vidéos (descendant)
    speaker_agg = speaker_agg.sort_values('videos', ascending=False)
    
    return speaker_agg

# Créer le DataFrame final des speakers
speaker_df = aggregate_speaker_data(expanded_df)



speaker_df.columns
speaker_df.shape

speaker_df.t_csv("speaker_dff.csv")

============================================================
DataFrame final des speakers :
============================================================
Nombre de speakers : 4759

Colonnes disponibles : ['speaker', 'video_ids', 'videos', 'views', 'topics', 'average_views']

Top 10 des speakers par nombre de vidéos :

(4759, 6)

In [18]:
speaker_df.to_csv("speaker_dff.csv")